#############################################################################
# Makefile for building: build/debug/YUView.app/Contents/MacOS/YUView
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  YUView.pro
# Template: app
# Command: /Users/jaeger/Qt/5.4/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile YUView.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../../Qt/5.4/clang_64/mkspecs/macx-clang -I. -I../../../Qt/5.4/clang_64/lib/QtOpenGL.framework/Versions/5/Headers -I../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../../Qt/5.4/clang_64/lib/QtXml.framework/Versions/5/Headers -I../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers -Ibuild/debug/.moc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -Ibuild/debug/.ui -F/Users/jaeger/Qt/5.4/clang_64/lib
QMAKE         = /Users/jaeger/Qt/5.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = YUView1.0.0
DISTDIR = /Users/jaeger/Documents/Coding/YUView/build/debug/.obj/YUView1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/jaeger/Qt/5.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/jaeger/Qt/5.4/clang_64/lib -framework QtOpenGL -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = build/debug/.obj/

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		renderwidget.cpp \
		yuvfile.cpp \
		yuvobject.cpp \
		yuvlistitem.cpp \
		yuvlistitemvid.cpp \
		yuviewapp.cpp \
		videofile.cpp \
		statisticsparser.cpp \
		statslistmodel.cpp \
		sliderdelegate.cpp \
		playlisttreewidget.cpp \
		statslistview.cpp \
		settingswindow.cpp build/debug/.qrc/qrc_images.cpp \
		build/debug/.qrc/qrc_resources.cpp \
		build/debug/.moc/moc_mainwindow.cpp \
		build/debug/.moc/moc_renderwidget.cpp \
		build/debug/.moc/moc_yuvobject.cpp \
		build/debug/.moc/moc_yuviewapp.cpp \
		build/debug/.moc/moc_statslistmodel.cpp \
		build/debug/.moc/moc_sliderdelegate.cpp \
		build/debug/.moc/moc_playlisttreewidget.cpp \
		build/debug/.moc/moc_statslistview.cpp \
		build/debug/.moc/moc_settingswindow.cpp
OBJECTS       = build/debug/.obj/main.o \
		build/debug/.obj/mainwindow.o \
		build/debug/.obj/renderwidget.o \
		build/debug/.obj/yuvfile.o \
		build/debug/.obj/yuvobject.o \
		build/debug/.obj/yuvlistitem.o \
		build/debug/.obj/yuvlistitemvid.o \
		build/debug/.obj/yuviewapp.o \
		build/debug/.obj/videofile.o \
		build/debug/.obj/statisticsparser.o \
		build/debug/.obj/statslistmodel.o \
		build/debug/.obj/sliderdelegate.o \
		build/debug/.obj/playlisttreewidget.o \
		build/debug/.obj/statslistview.o \
		build/debug/.obj/settingswindow.o \
		build/debug/.obj/qrc_images.o \
		build/debug/.obj/qrc_resources.o \
		build/debug/.obj/moc_mainwindow.o \
		build/debug/.obj/moc_renderwidget.o \
		build/debug/.obj/moc_yuvobject.o \
		build/debug/.obj/moc_yuviewapp.o \
		build/debug/.obj/moc_statslistmodel.o \
		build/debug/.obj/moc_sliderdelegate.o \
		build/debug/.obj/moc_playlisttreewidget.o \
		build/debug/.obj/moc_statslistview.o \
		build/debug/.obj/moc_settingswindow.o
DIST          = ../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		YUView.pro mainwindow.h \
		renderwidget.h \
		yuvfile.h \
		yuvobject.h \
		yuvlistitem.h \
		yuvlistitemvid.h \
		yuviewapp.h \
		videofile.h \
		statisticsparser.h \
		statslistmodel.h \
		sliderdelegate.h \
		playlisttreewidget.h \
		statslistview.h \
		settingswindow.h main.cpp \
		mainwindow.cpp \
		renderwidget.cpp \
		yuvfile.cpp \
		yuvobject.cpp \
		yuvlistitem.cpp \
		yuvlistitemvid.cpp \
		yuviewapp.cpp \
		videofile.cpp \
		statisticsparser.cpp \
		statslistmodel.cpp \
		sliderdelegate.cpp \
		playlisttreewidget.cpp \
		statslistview.cpp \
		settingswindow.cpp
QMAKE_TARGET  = YUView
DESTDIR       = build/debug/#avoid trailing-slash linebreak
TARGET        = build/debug/YUView.app/Contents/MacOS/YUView

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_settingswindow.h $(OBJECTS)  
	@test -d build/debug/YUView.app/Contents/MacOS/ || mkdir -p build/debug/YUView.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: YUView.pro ../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.4/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/uic.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.4/clang_64/mkspecs/features/lex.prf \
		YUView.pro \
		images.qrc \
		resources.qrc \
		/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl \
		/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/QtXml.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile YUView.pro
../../../Qt/5.4/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.4/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.4/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.4/clang_64/mkspecs/common/shell-unix.conf:
../../../Qt/5.4/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.4/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.4/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.4/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.4/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.4/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.4/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.4/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.4/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.4/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.4/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.4/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.4/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.4/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.4/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.4/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.4/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.4/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.4/clang_64/mkspecs/features/uic.prf:
../../../Qt/5.4/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.4/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.4/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.4/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.4/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.4/clang_64/mkspecs/features/lex.prf:
YUView.pro:
images.qrc:
resources.qrc:
/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/QtCore.prl:
/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/QtXml.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 -o Makefile YUView.pro

qmake_all: FORCE

build/debug/YUView.app/Contents/PkgInfo: 
	@test -d build/debug/YUView.app/Contents || mkdir -p build/debug/YUView.app/Contents
	@$(DEL_FILE) build/debug/YUView.app/Contents/PkgInfo
	@echo "APPL????" >build/debug/YUView.app/Contents/PkgInfo
build/debug/YUView.app/Contents/Resources/empty.lproj: 
	@test -d build/debug/YUView.app/Contents/Resources || mkdir -p build/debug/YUView.app/Contents/Resources
	@touch build/debug/YUView.app/Contents/Resources/empty.lproj
	
build/debug/YUView.app/Contents/Info.plist: 
	@test -d build/debug/YUView.app/Contents || mkdir -p build/debug/YUView.app/Contents
	@$(DEL_FILE) build/debug/YUView.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.chungwasoft.YUView,g" -e "s,@ICON@,YUView.icns,g" -e "s,@EXECUTABLE@,YUView,g" -e "s,@TYPEINFO@,????,g" Info.plist >build/debug/YUView.app/Contents/Info.plist
build/debug/YUView.app/Contents/Resources/YUView.icns: images/YUView.icns
	@test -d build/debug/YUView.app/Contents/Resources/ || mkdir -p build/debug/YUView.app/Contents/Resources/
	@$(DEL_FILE) build/debug/YUView.app/Contents/Resources/YUView.icns
	@$(COPY_FILE) images/YUView.icns build/debug/YUView.app/Contents/Resources/YUView.icns

all: Makefile \
		build/debug/YUView.app/Contents/PkgInfo \
		build/debug/YUView.app/Contents/Resources/empty.lproj \
		build/debug/YUView.app/Contents/Info.plist \
		build/debug/YUView.app/Contents/Resources/YUView.icns $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h renderwidget.h yuvfile.h yuvobject.h yuvlistitem.h yuvlistitemvid.h yuviewapp.h videofile.h statisticsparser.h statslistmodel.h sliderdelegate.h playlisttreewidget.h statslistview.h settingswindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp renderwidget.cpp yuvfile.cpp yuvobject.cpp yuvlistitem.cpp yuvlistitemvid.cpp yuviewapp.cpp videofile.cpp statisticsparser.cpp statslistmodel.cpp sliderdelegate.cpp playlisttreewidget.cpp statslistview.cpp settingswindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui settingswindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r build/debug/YUView.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: build/debug/.qrc/qrc_images.cpp build/debug/.qrc/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/debug/.qrc/qrc_images.cpp build/debug/.qrc/qrc_resources.cpp
build/debug/.qrc/qrc_images.cpp: images.qrc \
		images/img_R.png \
		images/img_repeat_on.png \
		images/stats.png \
		images/img_play.png \
		images/img_pause.png \
		images/stats_remove.png \
		images/img_folder.png \
		images/Y_on.png \
		images/img_television.png \
		images/U.png \
		images/V_on.png \
		images/V.png \
		images/YUView.icns \
		images/stats_add.png \
		images/img_delete.png \
		images/img_stereo.png \
		images/Y.png \
		images/img_repeat.png \
		images/U_on.png \
		images/img_folder_add.png \
		images/img_stop.png \
		images/img_L.png
	/Users/jaeger/Qt/5.4/clang_64/bin/rcc -name images images.qrc -o build/debug/.qrc/qrc_images.cpp

build/debug/.qrc/qrc_resources.cpp: resources.qrc \
		docs/about.html
	/Users/jaeger/Qt/5.4/clang_64/bin/rcc -name resources resources.qrc -o build/debug/.qrc/qrc_resources.cpp

compiler_moc_header_make_all: build/debug/.moc/moc_mainwindow.cpp build/debug/.moc/moc_renderwidget.cpp build/debug/.moc/moc_yuvobject.cpp build/debug/.moc/moc_yuviewapp.cpp build/debug/.moc/moc_statslistmodel.cpp build/debug/.moc/moc_sliderdelegate.cpp build/debug/.moc/moc_playlisttreewidget.cpp build/debug/.moc/moc_statslistview.cpp build/debug/.moc/moc_settingswindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/.moc/moc_mainwindow.cpp build/debug/.moc/moc_renderwidget.cpp build/debug/.moc/moc_yuvobject.cpp build/debug/.moc/moc_yuviewapp.cpp build/debug/.moc/moc_statslistmodel.cpp build/debug/.moc/moc_sliderdelegate.cpp build/debug/.moc/moc_playlisttreewidget.cpp build/debug/.moc/moc_statslistview.cpp build/debug/.moc/moc_settingswindow.cpp
build/debug/.moc/moc_mainwindow.cpp: ../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		playlisttreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		renderwidget.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		mainwindow.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib mainwindow.h -o build/debug/.moc/moc_mainwindow.cpp

build/debug/.moc/moc_renderwidget.cpp: ../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		renderwidget.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib renderwidget.h -o build/debug/.moc/moc_renderwidget.cpp

build/debug/.moc/moc_yuvobject.cpp: ../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		yuvobject.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib yuvobject.h -o build/debug/.moc/moc_yuvobject.cpp

build/debug/.moc/moc_yuviewapp.cpp: ../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		mainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		playlisttreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		renderwidget.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		yuviewapp.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib yuviewapp.h -o build/debug/.moc/moc_yuviewapp.cpp

build/debug/.moc/moc_statslistmodel.cpp: ../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QAbstractListModel \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractitemmodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMimeData \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		statisticsparser.h \
		statslistmodel.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib statslistmodel.h -o build/debug/.moc/moc_statslistmodel.cpp

build/debug/.moc/moc_sliderdelegate.cpp: ../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QItemDelegate \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		sliderdelegate.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib sliderdelegate.h -o build/debug/.moc/moc_sliderdelegate.cpp

build/debug/.moc/moc_playlisttreewidget.cpp: ../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		playlisttreewidget.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib playlisttreewidget.h -o build/debug/.moc/moc_playlisttreewidget.cpp

build/debug/.moc/moc_statslistview.cpp: ../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListView \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		statslistview.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib statslistview.h -o build/debug/.moc/moc_statslistview.cpp

build/debug/.moc/moc_settingswindow.cpp: ../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		settingswindow.h
	/Users/jaeger/Qt/5.4/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/jaeger/Qt/5.4/clang_64/mkspecs/macx-clang -I/Users/jaeger/Documents/Coding/YUView -I/Users/jaeger/Qt/5.4/clang_64/lib/QtOpenGL.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtGui.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtXml.framework/Headers -I/Users/jaeger/Qt/5.4/clang_64/lib/QtCore.framework/Headers -F/Users/jaeger/Qt/5.4/clang_64/lib settingswindow.h -o build/debug/.moc/moc_settingswindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_settingswindow.h
compiler_uic_clean:
	-$(DEL_FILE) build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_settingswindow.h
build/debug/.ui/ui_mainwindow.h: mainwindow.ui \
		renderwidget.h \
		playlisttreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h
	/Users/jaeger/Qt/5.4/clang_64/bin/uic mainwindow.ui -o build/debug/.ui/ui_mainwindow.h

build/debug/.ui/ui_settingswindow.h: settingswindow.ui
	/Users/jaeger/Qt/5.4/clang_64/bin/uic settingswindow.ui -o build/debug/.ui/ui_settingswindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/debug/.obj/main.o: main.cpp yuviewapp.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		mainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		playlisttreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		renderwidget.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/main.o main.cpp

build/debug/.obj/mainwindow.o: mainwindow.cpp mainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		playlisttreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		renderwidget.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		build/debug/.ui/ui_mainwindow.h \
		version.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QFileDialog \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QThread \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qthread.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QInputDialog \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QDesktopServices \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qdesktopservices.h \
		yuvlistitemvid.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		yuvlistitem.h \
		statslistmodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QAbstractListModel \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractitemmodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMimeData \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		sliderdelegate.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QItemDelegate \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/mainwindow.o mainwindow.cpp

build/debug/.obj/renderwidget.o: renderwidget.cpp renderwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QTextDocument \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocument.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMimeData \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		mainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		playlisttreewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/renderwidget.o renderwidget.cpp

build/debug/.obj/yuvfile.o: yuvfile.cpp yuvfile.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDir \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/yuvfile.o yuvfile.cpp

build/debug/.obj/yuvobject.o: yuvobject.cpp yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		yuvfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/yuvobject.o yuvobject.cpp

build/debug/.obj/yuvlistitem.o: yuvlistitem.cpp yuvlistitem.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		yuvlistitemvid.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/yuvlistitem.o yuvlistitem.cpp

build/debug/.obj/yuvlistitemvid.o: yuvlistitemvid.cpp yuvlistitemvid.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidgetItem \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		yuvlistitem.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/yuvlistitemvid.o yuvlistitemvid.cpp

build/debug/.obj/yuviewapp.o: yuviewapp.cpp yuviewapp.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		mainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		playlisttreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		renderwidget.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/yuviewapp.o yuviewapp.cpp

build/debug/.obj/videofile.o: videofile.cpp videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDir \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdir.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/videofile.o videofile.cpp

build/debug/.obj/statisticsparser.o: statisticsparser.cpp statisticsparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/statisticsparser.o statisticsparser.cpp

build/debug/.obj/statslistmodel.o: statslistmodel.cpp statslistmodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QAbstractListModel \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qabstractitemmodel.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QVector \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qvector.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QStringList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstringlist.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMimeData \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		statisticsparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/statslistmodel.o statslistmodel.cpp

build/debug/.obj/sliderdelegate.o: sliderdelegate.cpp sliderdelegate.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QItemDelegate \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QSpinBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qspinbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/sliderdelegate.o sliderdelegate.cpp

build/debug/.obj/playlisttreewidget.o: playlisttreewidget.cpp playlisttreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QDragEnterEvent \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMimeData \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimedata.h \
		mainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		renderwidget.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/playlisttreewidget.o playlisttreewidget.cpp

build/debug/.obj/statslistview.o: statslistview.cpp statslistview.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListView \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		mainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QListWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QList \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qlist.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QAction \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qaction.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenu \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMenuBar \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QString \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qstring.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qdatetime.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QTreeWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QDesktopWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QKeyEvent \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		playlisttreewidget.h \
		../../../Qt/5.4/clang_64/lib/QtGui.framework/Versions/5/Headers/QMouseEvent \
		renderwidget.h \
		yuvobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QObject \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qobject.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QByteArray \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qbytearray.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFileInfo \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfileinfo.h \
		videofile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QFile \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qfile.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QDateTime \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QCache \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qcache.h \
		statisticsparser.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QUrl \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qurl.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QMimeData \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qmimedata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/statslistview.o statslistview.cpp

build/debug/.obj/settingswindow.o: settingswindow.cpp settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QWidget \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/QSettings \
		../../../Qt/5.4/clang_64/lib/QtCore.framework/Versions/5/Headers/qsettings.h \
		build/debug/.ui/ui_settingswindow.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMessageBox \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QColorDialog \
		../../../Qt/5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qcolordialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/settingswindow.o settingswindow.cpp

build/debug/.obj/qrc_images.o: build/debug/.qrc/qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/qrc_images.o build/debug/.qrc/qrc_images.cpp

build/debug/.obj/qrc_resources.o: build/debug/.qrc/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/qrc_resources.o build/debug/.qrc/qrc_resources.cpp

build/debug/.obj/moc_mainwindow.o: build/debug/.moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_mainwindow.o build/debug/.moc/moc_mainwindow.cpp

build/debug/.obj/moc_renderwidget.o: build/debug/.moc/moc_renderwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_renderwidget.o build/debug/.moc/moc_renderwidget.cpp

build/debug/.obj/moc_yuvobject.o: build/debug/.moc/moc_yuvobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_yuvobject.o build/debug/.moc/moc_yuvobject.cpp

build/debug/.obj/moc_yuviewapp.o: build/debug/.moc/moc_yuviewapp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_yuviewapp.o build/debug/.moc/moc_yuviewapp.cpp

build/debug/.obj/moc_statslistmodel.o: build/debug/.moc/moc_statslistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_statslistmodel.o build/debug/.moc/moc_statslistmodel.cpp

build/debug/.obj/moc_sliderdelegate.o: build/debug/.moc/moc_sliderdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_sliderdelegate.o build/debug/.moc/moc_sliderdelegate.cpp

build/debug/.obj/moc_playlisttreewidget.o: build/debug/.moc/moc_playlisttreewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_playlisttreewidget.o build/debug/.moc/moc_playlisttreewidget.cpp

build/debug/.obj/moc_statslistview.o: build/debug/.moc/moc_statslistview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_statslistview.o build/debug/.moc/moc_statslistview.cpp

build/debug/.obj/moc_settingswindow.o: build/debug/.moc/moc_settingswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_settingswindow.o build/debug/.moc/moc_settingswindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

