name: yuview
version: 2.12.1
summary: YUView
description: YUView - The free cross platform YUV viewer and video analysis tool

apps:
  application:
    command: qt5-launch yuview
    plugs:
      - unity7
      - home

parts:
  application:
    plugin: qmake
    source: ./
    project-files: [YUView.pro]
    qt-version: qt5
    build-packages:
      - qtbase5-dev
      - libqt5gui5
      - libqt5opengl5
      - libqt5xml5
      - libqt5concurrent5
      - libqt5network5
      - libqt5core5a
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - qtbase5-dev
      - libqt5opengl5
    after: [qt5conf] # A wiki part
